name: Build ebook

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r script/requirements.txt

    - name: Build epub
      run: |
        python script/make_epub.py

    - name: download html_help_workshop
      run: |
        curl https://github.com/cayi-77/html_help_workshop_achive/raw/main/html_help_workshop.zip -L > hhh.zip
        7z x hhh.zip
        ls

    - name: Build chm
      run: |
        $env:Path += ';.' 
        python script/make_chm.py